os:
  - linux
sudo: required
dist: trusty
language: node_js
node_js:
  - "10"
addons:
  chrome: stable
install:
  - npm install
script:
  - npm run test
after_success:
  - node node_modules/coveralls/bin/coveralls.js < coverage/lcov.info
notifications:
  email: false
